[hls]
relative_roots=D:/DVCon/Vitis/systolic_array_v1
# Inferred from performance & pipeline pragmas/directives
syn.directive.loop_flatten=mmult/VITIS_LOOP_33_1  
syn.directive.loop_flatten=mmult/VITIS_LOOP_59_3  


